apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  USERNAME: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  API_KEY: ZXhhbXBsZS1hcGkta2V5LTEyMzQ1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: nexus-repo/backend-test-trabajo:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
